import * as React from 'react';
import { Bubble, BUBBLE_CORNER_RADIUS, BUBBLE_STROKE_WIDTH, type BubbleProps } from '../../atoms/Bubble';
import { openPolylineBoundary, generateWobbleRibbon, toClosedPath, type Point } from '../../../../sketch';
import { useElementSize } from '../../useElementSize';
import { STROKE_FREQUENCY, STROKE_WIGGLE, STROKE_WIDTH_VARIANCE } from '../../strokeDefaults';
import styles from './DialogueBubble.module.css';

/**
 * The 9-point grid used by CSS object-position/background-position, reused
 * here as a tooltip-style placement: each point names an edge (or corner) of
 * the Bubble the tail points from. 'center' has no edge of its own — a tail
 * can't point at the bubble's own middle — so it's an alias for 'bottom',
 * the conventional default for a chat bubble.
 */
export type DialogueBubblePlacement =
  | 'top-left'
  | 'top'
  | 'top-right'
  | 'left'
  | 'center'
  | 'right'
  | 'bottom-left'
  | 'bottom'
  | 'bottom-right';

const EDGE_OF: Record<DialogueBubblePlacement, 'top' | 'right' | 'bottom' | 'left'> = {
  'top-left': 'top',
  top: 'top',
  'top-right': 'top',
  left: 'left',
  center: 'bottom',
  right: 'right',
  'bottom-left': 'bottom',
  bottom: 'bottom',
  'bottom-right': 'bottom',
};

// Where along that edge, as a 0-1 fraction before clamping away from the corners.
const ALIGN_OF: Record<DialogueBubblePlacement, number> = {
  'top-left': 0,
  top: 0.5,
  'top-right': 1,
  left: 0.5,
  center: 0.5,
  right: 0.5,
  'bottom-left': 0,
  bottom: 0.5,
  'bottom-right': 1,
};

const ROTATION_OF: Record<'top' | 'right' | 'bottom' | 'left', number> = {
  bottom: 0,
  left: 90,
  top: 180,
  right: 270,
};

const TAIL_SIZE = 20;

/**
 * A real hand-drawn nub is never a mirrored isoceles triangle — it's a
 * scalene shape with a clearly obtuse-leaning point: one edge short and
 * steep, the other long and shallow, so the apex reads as "flicked" toward
 * one side rather than dropped straight down the middle. Fixed (not
 * randomized), so the tail looks the same every render; the organic feel
 * comes from `generateWobbleRibbon` perturbing this base shape, not from
 * re-rolling the shape itself.
 */
const TAIL_BASE_LEFT: Point = { x: 2, y: 0 };
const TAIL_APEX: Point = { x: 7, y: TAIL_SIZE - 1 };
const TAIL_BASE_RIGHT: Point = { x: 17.5, y: 0 };
/**
 * Two extra points beyond each base corner, angled outward and up into the
 * bubble's own border band (negative y). Without them the tail's ribbon
 * ends exactly at the seam, and since it's generated independently from the
 * bubble's own outline, their wobble noise never lines up there — the seam
 * reads as a visible kink. Flaring the ribbon itself past the seam so it
 * overlaps the bubble's border turns that hard edge into an overlap, which
 * is what actually reads as one continuous union rather than two shapes
 * touching. `smoothPass` (see wobble.ts) holds an open boundary's true
 * endpoints fixed but smooths everything between them, so making these
 * flares the endpoints instead of the base corners also rounds the base
 * corners themselves into the curve rather than leaving them as sharp
 * vertices.
 */
const TAIL_FLARE_LEFT: Point = { x: -1, y: -(BUBBLE_STROKE_WIDTH * 1.2) };
const TAIL_FLARE_RIGHT: Point = { x: 20.5, y: -(BUBBLE_STROKE_WIDTH * 1.2) };
/** How far the fill's outermost points extend above y=0 to merge into the bubble, clear of the wobble's own reach. */
const TAIL_BACK_OVERSHOOT = BUBBLE_STROKE_WIDTH * 1.2 + 1;

const tailRibbon = generateWobbleRibbon(
  openPolylineBoundary([TAIL_FLARE_LEFT, TAIL_BASE_LEFT, TAIL_APEX, TAIL_BASE_RIGHT, TAIL_FLARE_RIGHT]),
  {
    seed: 9,
    halfWidth: BUBBLE_STROKE_WIDTH / 2,
    wiggle: STROKE_WIGGLE,
    frequency: STROKE_FREQUENCY,
    smoothen: 0.55,
    widthVariance: STROKE_WIDTH_VARIANCE,
    closed: false,
  },
);

const tailFillPath = (() => {
  const outer = [...tailRibbon.outer];
  outer[0] = { ...outer[0], y: -TAIL_BACK_OVERSHOOT };
  outer[outer.length - 1] = { ...outer[outer.length - 1], y: -TAIL_BACK_OVERSHOOT };
  return toClosedPath(outer);
})();

export interface DialogueBubbleProps extends BubbleProps {
  /**
   * Which edge (and where along it) the tail points from, using the same
   * 9-point grid as CSS object-position. Clamped at render time so the tail
   * can only land on the straight run of that edge — like a tooltip arrow,
   * it never points into the bubble's curved corner.
   * @default 'bottom'
   */
  placement?: DialogueBubblePlacement;
  /** Hide the tail to get a plain hand-drawn pill (equivalent to rendering a bare Bubble). */
  showTail?: boolean;
}

/**
 * A Bubble with a tail attached using tooltip-anchor positioning: the Bubble
 * is the "anchor" element, its rendered box is measured live, and the tail —
 * an asymmetric nub generated by the same wobble-ribbon engine as Bubble's
 * own outline, not a hand-cropped chunk of a bigger shape — is placed and
 * clamped against that measurement so it always lands on a straight run and
 * overlaps the bubble's own border, the same anchor + clamp pattern a
 * tooltip uses to keep its arrow pinned to its trigger.
 */
export const DialogueBubble = React.forwardRef<HTMLDivElement, DialogueBubbleProps>(
  function DialogueBubble({ placement = 'bottom', showTail = true, className, ...props }, ref) {
    const [setRef, anchor] = useElementSize<HTMLDivElement>(ref);

    const edge = EDGE_OF[placement];
    const isHorizontalEdge = edge === 'top' || edge === 'bottom';
    const runLength = isHorizontalEdge ? anchor.width : anchor.height;
    const align = ALIGN_OF[placement];

    const raw = align * runLength;
    const along =
      runLength > 0 ? Math.min(Math.max(raw, BUBBLE_CORNER_RADIUS), runLength - BUBBLE_CORNER_RADIUS) : raw;

    const tailStyle: React.CSSProperties = { transform: `rotate(${ROTATION_OF[edge]}deg)` };
    if (isHorizontalEdge) {
      tailStyle.left = `${along}px`;
      tailStyle[edge === 'top' ? 'bottom' : 'top'] = `calc(100% - ${BUBBLE_STROKE_WIDTH}px)`;
      tailStyle.marginLeft = -TAIL_SIZE / 2;
    } else {
      tailStyle.top = `${along}px`;
      tailStyle.left =
        edge === 'left' ? `${-(TAIL_SIZE - BUBBLE_STROKE_WIDTH)}px` : `calc(100% - ${BUBBLE_STROKE_WIDTH}px)`;
      tailStyle.marginTop = -TAIL_SIZE / 2;
    }

    return (
      <span className={styles.wrapper}>
        <Bubble ref={setRef} className={className} {...props} />
        {showTail && anchor.width > 0 && (
          <svg
            className={styles.tail}
            style={tailStyle}
            width={TAIL_SIZE}
            height={TAIL_SIZE}
            viewBox={`0 0 ${TAIL_SIZE} ${TAIL_SIZE}`}
            aria-hidden
          >
            {/*
              Two paths: a solid fill (no stroke) whose base corners sit above
              y=0, hidden under the bubble's own overlap, and the ribbon path
              tracing just the two slanted sides — never the back edge, which
              would otherwise draw a second, redundant line (and a sliver of
              white) right where the tail is meant to read as one continuous
              outline with the bubble.
            */}
            <path d={tailFillPath} fill="var(--color-brand-white)" />
            <path d={tailRibbon.ribbonPath} fill="var(--color-brand-brown)" fillRule="evenodd" />
          </svg>
        )}
      </span>
    );
  },
);
